### ISSUE TITLE
ModuleNotFoundError: No module named 'transformer'

### ISSUE THREAD

**Issue by Narabzad** [Wendy-Xiao/summ_guided_disco_parser#1]
Hello,
  
  Thanks or your great work. 
  
  I have a problem when running `python3 main_dep.py -n_layers 6 -n_head 8 -device 0 -model_name cnndm-6-8` . I get the following error :
```
Traceback (most recent call last):
  File "main_dep.py", line 12, in <module>
    from models_dp import DiscoExtSumm_dp
  File "/home/t-negara/summ_guided_disco_parser/models_dp.py", line 14, in <module>
    from transformer.EncoderForSumm import *
ModuleNotFoundError: No module named 'transformer'
```
apparently there is something wrong with `transformer.EncoderForSumm import *` line in main_dep.py.
Any idea?

**Comment by Wendy-Xiao** [comment]
Oh yeah, I think I forgot to upload the transformer folder, I'll fix it now.
